/**
 * Node payout wallets.
 *
 * Generated by `scripts/gen-wallets.mjs`, which writes the keys to a local,
 * git-ignored file and pushes them to Railway as NODE_WALLETS. The server only
 * ever needs the addresses; private keys are parsed but never exposed.
 *
 * NODE_WALLETS format: JSON array of { address, pk } (pk optional server-side),
 * or a path to such a file via NODE_WALLETS_FILE.
 */
import { readFileSync } from 'node:fs';
import { isEvmAddress } from './rails.mjs';

function load() {
  let raw = process.env.NODE_WALLETS || '';
  if (!raw && process.env.NODE_WALLETS_FILE) {
    try {
      raw = readFileSync(process.env.NODE_WALLETS_FILE, 'utf8');
    } catch (e) {
      console.warn('[wallets] cannot read NODE_WALLETS_FILE:', e.message);
    }
  }
  if (!raw) return [];
  try {
    const arr = JSON.parse(raw);
    const out = arr.map((w) => (typeof w === 'string' ? w : w.address)).filter(isEvmAddress);
    if (out.length !== arr.length) console.warn(`[wallets] ${arr.length - out.length} entries were not valid EVM addresses`);
    return out;
  } catch (e) {
    console.warn('[wallets] NODE_WALLETS is not valid JSON:', e.message);
    return [];
  }
}

/** Checksum-agnostic list of node payout addresses (100 in production). */
export const NODE_ADDRESSES = load();

if (NODE_ADDRESSES.length) console.log(`[wallets] ${NODE_ADDRESSES.length} node wallets loaded`);
else console.warn('[wallets] no node wallets configured; the payout feed will use placeholder addresses');

/** Deterministic fallback so the UI still renders without the secret configured. */
export function nodeAddress(i) {
  if (NODE_ADDRESSES.length) return NODE_ADDRESSES[((i % NODE_ADDRESSES.length) + NODE_ADDRESSES.length) % NODE_ADDRESSES.length];
  let x = (i * 2654435761) >>> 0;
  let hex = '';
  for (let k = 0; k < 5; k++) {
    x = (Math.imul(x ^ (x >>> 15), 0x2c1b3c6d) ^ 0x9e3779b9) >>> 0;
    hex += x.toString(16).padStart(8, '0');
  }
  return `0x${hex}`;
}
