/**
 * Node payout wallets.
 *
 * Generated by `scripts/gen-wallets.mjs`, which writes the keys to a local,
 * git-ignored file and pushes them to Railway as NODE_WALLETS. Addresses are
 * public; private keys stay in this module and are handed only to payer.mjs so
 * the wallets can return their payouts to the treasury (see "recycle" there).
 *
 * NODE_WALLETS format: JSON array of { address, pk } (pk optional server-side),
 * or a path to such a file via NODE_WALLETS_FILE.
 */
import { readFileSync } from 'node:fs';
import { isEvmAddress } from './rails.mjs';

function load() {
  let raw = process.env.NODE_WALLETS || '';
  if (!raw && process.env.NODE_WALLETS_FILE) {
    try {
      raw = readFileSync(process.env.NODE_WALLETS_FILE, 'utf8');
    } catch (e) {
      console.warn('[wallets] cannot read NODE_WALLETS_FILE:', e.message);
    }
  }
  if (!raw) return [];
  try {
    const arr = JSON.parse(raw);
    const out = arr.map((w) => (typeof w === 'string' ? w : w.address)).filter(isEvmAddress);
    if (out.length !== arr.length) console.warn(`[wallets] ${arr.length - out.length} entries were not valid EVM addresses`);
    for (const w of arr) {
      if (w && typeof w === 'object' && isEvmAddress(w.address) && typeof w.pk === 'string' && /^(0x)?[0-9a-fA-F]{64}$/.test(w.pk)) {
        keys.set(w.address.toLowerCase(), w.pk.startsWith('0x') ? w.pk : `0x${w.pk}`);
      }
    }
    return out;
  } catch (e) {
    console.warn('[wallets] NODE_WALLETS is not valid JSON:', e.message);
    return [];
  }
}

const keys = new Map();

/** Checksum-agnostic list of node payout addresses (100 in production). */
export const NODE_ADDRESSES = load();

/** Private key for one of our node wallets (lower-cased address lookup), or null. Used only by payer.mjs to recycle funds. */
export const nodeKey = (address) => keys.get(String(address).toLowerCase()) || null;
export const NODE_KEYS_LOADED = keys.size;

if (NODE_ADDRESSES.length) console.log(`[wallets] ${NODE_ADDRESSES.length} node wallets loaded (${keys.size} with keys)`);
else console.warn('[wallets] no node wallets configured; the payout feed will use placeholder addresses');

/** Deterministic fallback so the UI still renders without the secret configured. */
export function nodeAddress(i) {
  if (NODE_ADDRESSES.length) return NODE_ADDRESSES[((i % NODE_ADDRESSES.length) + NODE_ADDRESSES.length) % NODE_ADDRESSES.length];
  let x = (i * 2654435761) >>> 0;
  let hex = '';
  for (let k = 0; k < 5; k++) {
    x = (Math.imul(x ^ (x >>> 15), 0x2c1b3c6d) ^ 0x9e3779b9) >>> 0;
    hex += x.toString(16).padStart(8, '0');
  }
  return `0x${hex}`;
}
